<?php
// ---------- Sample data (replace with DB rows if you like) ----------
$tables = [
    ["code"=>"Population_Age_Sex","title"=>"A-01: ) POPULATION BY AGE AND SEX","series"=>"Age pyramid for one selected population. Available by state, district, and residence (urban/rural)
"],
    ["code"=>"age_group","title"=>"A-02: POPULATION BY AGE AND SEX, AND SEX RATIO","series"=>"Age pyramid for one selected population. Available by state and district, residence (urban/rural). The pyramid applies a color coding to display the sex ratio for each age group.
"],
    ["code"=>"gender","title"=>"A-03: gender of gujrat and disrtict and subdistict","series"=>"gender conut"],

    ["code"=>"edu","title"=>"A-04:POPULATION BY  AGE GROUP, SEX, AREA OF RESIDENCE AND EDUCATION LEVEL","series"=>"This punch card chart displays the population of all States/UTs by age group in the form of bubbles whose size is proportional to the corresponding population. The chart can be generated by sex, education level, type of population (all, scheduled Castes, scheduled Tribes), and area of residence (all, rural, urban).
."],
    ["code"=>"chidern_age_plot","title"=>"A-05 NUMBER OF CHILDREN EVER-HAD BY AGE","series"=>"This vertical-dot chart displays the number of children ever-had, as declared, by age of the mother and sex of the child. The size of the dots is proportional to the number of children. The charts can be generated by State/UT, area of residence (all, rural, urban), and type of population (all, scheduled Castes, scheduled Tribes). They show a systematic excess of boys over girls.
"],
    ["code"=>"working","title"=>"A-06: WORKERS BY STATE AND INDUSTRY
","series"=>"This scatter plot displays the working male and female populations of a selected State/UT in the form of dots whose size represents the corresponding population size. The plot can be generated by area of residence (all, rural, urban).
"],
    ["code"=>"religion","title"=>"A-07: religion of gujrat and disrtict and subdistict","series"=>"religion conut"],
    ["code"=>"caste","title"=>"A-08: caste of gujrat and disrtict and subdistict","series"=>"caste conut"],

];

$allSeries = [];

// ---------- Read filters ----------
$q        = isset($_GET['q']) ? trim($_GET['q']) : "";
$selected = isset($_GET['series']) ? (array)$_GET['series'] : [];

// ---------- Filter ----------
$filtered = array_values(array_filter($tables, function($row) use ($q, $selected){
    $ok = true;
    if ($q !== "") {
        $ok = stripos($row['title'], $q) !== false || stripos($row['code'], $q) !== false;
    }
    if ($ok && $selected) {
        $ok = in_array($row['series'], $selected, true);
    }
    return $ok;
}));

// ---------- Pagination ----------
$perPage = 6;
$total   = count($filtered);
$page    = max(1, intval($_GET['page'] ?? 1));
$pages   = max(1, (int)ceil($total / $perPage));
$page    = min($page, $pages);
$start   = ($page - 1) * $perPage;
$rows    = array_slice($filtered, $start, $perPage);

// Helper to keep query string while changing page
function pageLink($p){
    $params = $_GET;
    $params['page'] = $p;
    return '?' . http_build_query($params);
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Census Tables — Orange Theme</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="Census_Tables.css">
</head>
<body>
<header class="topbar">
  <div class="brand">CENSUS TABLES</div>
  <form class="search" method="get">
    <input type="text" name="q" placeholder="Search tables…" value="<?=htmlspecialchars($q)?>">
    <!-- <?php foreach ($selected as $s): ?>
      <input type="hidden" name="series[]" value="<?=htmlspecialchars($s)?>">
    <?php endforeach; ?> -->
    <button type="submit">Search</button>
  </form>
</header>

<main class="container">
  <aside class="sidebar">
    <h3>Census year</h3>
    <label class="check"><input type="checkbox"> 2031</label>

    <!-- <h3>Table series</h3>
    <form method="get" class="filters">
      <input type="hidden" name="q" value="<?=htmlspecialchars($q)?>">
      <div class="scroll">
<?php foreach($allSeries as $s): ?>
          <label class="check">
            <input type="checkbox" name="series[]" value="<?=htmlspecialchars($s)?>" <?= in_array($s,$selected,true) ? 'checked' : '' ?>>
            <?= htmlspecialchars($s) ?>
          </label>
        <?php endforeach; ?>
      </div> -->
      <button class="apply" type="submit">Apply filters</button>
      <?php if ($selected || $q !== ""): ?>
        <a class="clear" href="?">Clear all</a>
      <?php endif; ?>
    </form>
  </aside>

  <section class="content">
    <div class="list-header">
      Showing <?= $total ? ($start+1) : 0 ?>–<?= min($start + $perPage, $total) ?> of <?= $total ?> tables
    </div>

    <ul class="cards">
      <!-- <?php foreach($rows as $row): ?> -->
        <li class="card">
          <div class="icon" aria-hidden="true">
            <!-- simple sheet icon -->
            <svg viewBox="0 0 24 24">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
              <line x1="3" y1="8" x2="21" y2="8"></line>
              <line x1="8" y1="8" x2="8" y2="21"></line>
            </svg>
          </div>
          <div class="meta">
            <div class="code"><?= htmlspecialchars($row['code']) ?></div>
            <a href="" class="title"><?= htmlspecialchars($row['title']) ?></a>
            <div class="series"><?= htmlspecialchars($row['series']) ?></div>
          </div>

    <a href="<?= htmlspecialchars($row['code']) ?>.php" class="pill">show</a>
        </li>
      <!-- <?php endforeach; ?> -->

      <?php if (!$rows): ?>
        <li class="empty">No tables match your filters.</li>
      <?php endif; ?>
    </ul>

    <nav class="pager" aria-label="Pagination">
      <a class="btn <?= $page<=1?'disabled':'' ?>" href="<?= $page>1 ? pageLink(1) : '#' ?>">&laquo; First</a>
      <a class="btn <?= $page<=1?'disabled':'' ?>" href="<?= $page>1 ? pageLink($page-1) : '#' ?>">&lsaquo; Prev</a>
      <span class="page-indicator">Page <?= $page ?> of <?= $pages ?></span>
      <a class="btn <?= $page>=$pages?'disabled':'' ?>" href="<?= $page<$pages ? pageLink($page+1) : '#' ?>">Next &rsaquo;</a>
      <a class="btn <?= $page>=$pages?'disabled':'' ?>" href="<?= $page<$pages ? pageLink($pages) : '#' ?>">Last &raquo;</a>
    </nav>
  </section>
</main>

<footer class="footer">© Census Demo UI</footer>
</body>
</html>